name: PathGen
version: 1.0
main: click.scheid.pathgen.PathGenPlugin
api-version: 1.21.7

commands:
  pathgen:
    description: "Interact with the pathgen plugin"
    usage: "/pathgen [path_name] [method] [args]"